// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fqsGNeQ-2h_UB8XxjZYpP5Z50TCrYW0',
    appId: '1:656099412987:web:2b822bc3b24def8d1cd95e',
    messagingSenderId: '656099412987',
    projectId: 'habitly-c0a50',
    authDomain: 'habitly-c0a50.firebaseapp.com',
    storageBucket: 'habitly-c0a50.firebasestorage.app',
    measurementId: 'G-YE47C78LXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM7oUWrtv_dyyz6AgaE5XobhLoHpjlGA8',
    appId: '1:656099412987:android:9c54ace375097e181cd95e',
    messagingSenderId: '656099412987',
    projectId: 'habitly-c0a50',
    storageBucket: 'habitly-c0a50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTOqJtg6peyDVeU1nK5fpOg_LupZx0-MA',
    appId: '1:656099412987:ios:be4704142a77d4111cd95e',
    messagingSenderId: '656099412987',
    projectId: 'habitly-c0a50',
    storageBucket: 'habitly-c0a50.firebasestorage.app',
    iosBundleId: 'com.example.mission5Habbits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTOqJtg6peyDVeU1nK5fpOg_LupZx0-MA',
    appId: '1:656099412987:ios:be4704142a77d4111cd95e',
    messagingSenderId: '656099412987',
    projectId: 'habitly-c0a50',
    storageBucket: 'habitly-c0a50.firebasestorage.app',
    iosBundleId: 'com.example.mission5Habbits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-fqsGNeQ-2h_UB8XxjZYpP5Z50TCrYW0',
    appId: '1:656099412987:web:5c99e5fb84539f291cd95e',
    messagingSenderId: '656099412987',
    projectId: 'habitly-c0a50',
    authDomain: 'habitly-c0a50.firebaseapp.com',
    storageBucket: 'habitly-c0a50.firebasestorage.app',
    measurementId: 'G-3YTLH0HSD9',
  );
}
